#!/bin/sh

USERS_FILE=$(readlink -f "${USERS_FILE:-"/etc/dovecot/users"}")
PASS_SCHEME="${PASS_SCHEME:-"ssha256"}"

usage() {
    cat << EOF
Change a user's password

Usage: $0 EMAIL PASSWORD

Users file(\$USERS_FILE): ${USERS_FILE}
Password scheme(\$PASS_SCHEME): ${PASS_SCHEME}
EOF
}

EMAIL=$1
PASS=$2

if [ -z "$EMAIL" ] || [ -z "$PASS" ] ; then
    usage
    exit 1
fi

if [ ! -f "${USERS_FILE}" ]; then
    echo "Users file not found(${USERS_FILE})!"
    exit 1
fi

cat "${USERS_FILE}" | grep -iq "^${EMAIL}"
if [ "$?" -ne "0" ] ; then
    echo "User doesn't exists!"
    exit 2
fi

HASH=$(doveadm pw -s ${PASS_SCHEME} -p "$PASS")

sed -i -e "s,${EMAIL}:[^:]*:,${EMAIL}:${HASH}:," "${USERS_FILE}"

echo "User's password changed successfully!"